version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:5000"
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=development
      - JWT_SECRET_KEY=super-secret
